/* Narra periodic reviews: weekly, monthly, quarterly, yearly.
   The draft is computed from the user's own entries and check-ins — nothing is generated by a model and nothing is invented.
   Every factual line carries the ids of the entries (or the days of the check-ins) it came from, so it can be opened and verified.
   The user's own notes live separately, so regenerating a draft never destroys them. Pure and dependency-free. */
import {dayKey,addDays,median,MIN_N,dayStates,daysBetween} from "./stats.mjs?v=4.2.0";
import {activeDimensions,dimValue,dimLabel,knownDimensions,DEFAULT_CONFIG} from "./checkin.mjs?v=4.2.0";
import {collectEntities,listByType,ENTITY_TYPES} from "./entities.mjs?v=4.2.0";
import {entryText,openChecklistItems,plural,excerpt} from "./text.mjs?v=4.2.0";
import {wordCount,capitalizeRu} from "./domain.mjs?v=4.2.0";

export const PERIOD_KINDS=[["week","Неделя"],["month","Месяц"],["quarter","Квартал"],["year","Год"]];
const MONTHS=["января","февраля","марта","апреля","мая","июня","июля","августа","сентября","октября","ноября","декабря"];
const MONTHS_NOM=["Январь","Февраль","Март","Апрель","Май","Июнь","Июль","Август","Сентябрь","Октябрь","Ноябрь","Декабрь"];
const pad=n=>String(n).padStart(2,"0");
const parts=key=>key.split("-").map(Number);
const dayLabel=key=>{const [,m,d]=parts(key);return `${d} ${MONTHS[m-1]}`;};
const SHORT=["янв.","февр.","мар.","апр.","мая","июн.","июл.","авг.","сент.","окт.","нояб.","дек."];
const shortMonth=m=>SHORT[m-1];

/** Period that contains `ref` (a Date). Weeks start on Monday. */
export function periodRange(kind,ref=new Date()){
  const key=dayKey(ref.toISOString?ref.toISOString():ref),[y,m,d]=parts(key);
  let from,to,id,label;
  if(kind==="week"){
    const dow=(new Date(`${key}T12:00:00`).getDay()+6)%7;
    from=addDays(key,-dow);to=addDays(from,6);id=`week:${from}`;
    const [,fm,fd]=parts(from),[,tm,td]=parts(to);
    label=fm===tm?`${fd}–${td} ${MONTHS[tm-1]}`:`${fd} ${shortMonth(fm)} – ${td} ${shortMonth(tm)}`;
  }else if(kind==="month"){
    from=`${y}-${pad(m)}-01`;to=addDays(`${m===12?y+1:y}-${pad(m===12?1:m+1)}-01`,-1);id=`month:${y}-${pad(m)}`;label=`${MONTHS_NOM[m-1]} ${y}`;
  }else if(kind==="quarter"){
    const q=Math.floor((m-1)/3);from=`${y}-${pad(q*3+1)}-01`;const nm=q*3+4;to=addDays(`${nm>12?y+1:y}-${pad(nm>12?1:nm)}-01`,-1);id=`quarter:${y}-Q${q+1}`;label=`${q+1}-й квартал ${y}`;
  }else{
    from=`${y}-01-01`;to=`${y}-12-31`;id=`year:${y}`;label=`${y} год`;
  }
  return {kind,id,from,to,label,days:daysBetween(from,to)+1};
}
export function shiftPeriod(range,delta){
  const {kind}=range;
  if(kind==="week") return periodRange("week",new Date(`${addDays(range.from,delta*7)}T12:00:00`));
  const [y,m]=parts(range.from);
  if(kind==="month"){const t=new Date(y,m-1+delta,1,12);return periodRange("month",t);}
  if(kind==="quarter"){const t=new Date(y,m-1+delta*3,1,12);return periodRange("quarter",t);}
  return periodRange("year",new Date(y+delta,0,1,12));
}
export const inRange=(iso,range)=>{const k=dayKey(iso);return k>=range.from&&k<=range.to;};

function hash(text){let h=2166136261;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619);}return (h>>>0).toString(36);}
const item=(section,text,{sourceIds=[],days=[]}={})=>({id:`${section}-${hash(text+sourceIds.join(","))}`,text,sourceIds,days});

const QUESTION_BANK={
  base:["Что из этого периода хочется унести с собой дальше?","Что оказалось важнее, чем казалось в начале?","Чему вы научились в этот период?","Что вы хотели бы сделать иначе — и что оставить как есть?"],
  quiet:["Что мешало писать чаще — или, может быть, ничего не мешало?","Какой день из этого периода вы бы записали, если бы могли вернуться?"],
  shift:["Что изменилось между началом и концом периода — снаружи и внутри?","Что могло быть связано с этими переменами? Это ваша гипотеза, не вывод."],
  theme:t=>[`Что для вас сейчас значит «${t}»?`,`Как тема «${t}» менялась за этот период?`],
  person:p=>[`Что вам хочется сказать или спросить у человека, которого вы называли чаще всего — «${p}»?`],
  loop:["Какую из незавершённых нитей вы хотите закрыть, а какую — отпустить?"],
};
function pickStable(list,seed,n){
  const start=parseInt(hash(seed),36)%Math.max(1,list.length),out=[];
  for(let i=0;i<list.length&&out.length<n;i++)out.push(list[(start+i)%list.length]);
  return out;
}

/** Build the factual draft for one period. `now` only decides which loops are still open. */
export function buildReview({range,entries,checkins,config=DEFAULT_CONFIG,chapters=[],notes=[],now=new Date()}){
  const inP=entries.filter(e=>!e.deletedAt&&inRange(e.happenedAt,range)).sort((a,b)=>new Date(a.happenedAt)-new Date(b.happenedAt));
  const chkP=checkins.filter(c=>inRange(c.observedAt,range));
  const wordsTotal=inP.reduce((s,e)=>s+wordCount(e.body),0);
  const activeDays=new Set(inP.map(e=>dayKey(e.happenedAt))).size;
  const stats={entries:inP.length,words:wordsTotal,activeDays,favorites:inP.filter(e=>e.favorite).length,periodDays:range.days};
  const title=e=>entryText(e,120).title;

  /* 1. what happened */
  const happened=[];
  if(inP.length){
    if(range.kind==="week"||inP.length<=8){
      for(const e of inP)happened.push(item("happened",`${dayLabel(dayKey(e.happenedAt))} — «${title(e)}»`,{sourceIds:[e.id]}));
    }else{
      const groupKey=range.kind==="month"?(e=>{const k=dayKey(e.happenedAt),dow=(new Date(`${k}T12:00:00`).getDay()+6)%7;return addDays(k,-dow);}):(e=>dayKey(e.happenedAt).slice(0,7));
      const groups=new Map();for(const e of inP){const g=groupKey(e);if(!groups.has(g))groups.set(g,[]);groups.get(g).push(e);}
      for(const [g,list] of groups){
        const label=range.kind==="month"?`Неделя с ${dayLabel(g)}`:capitalizeRu(MONTHS_NOM[parts(`${g}-01`)[1]-1].toLocaleLowerCase("ru-RU"));
        const top=list.find(e=>e.favorite)||list.slice().sort((a,b)=>wordCount(b.body)-wordCount(a.body))[0];
        happened.push(item("happened",`${label}: ${list.length} ${plural.entry(list.length)}, среди них «${title(top)}»`,{sourceIds:list.map(e=>e.id)}));
      }
    }
  }

  /* 2. people, places, themes */
  const ents=collectEntities(inP,notes),entityItems=[];
  for(const {type,plural:pl} of ENTITY_TYPES){
    const top=listByType(ents,type).filter(r=>r.count>=(type==="theme"?2:1)).slice(0,4);
    if(!top.length) continue;
    entityItems.push(item("entities",`${pl}: ${top.map(r=>`${r.name} (${r.count})`).join(", ")}`,{sourceIds:[...new Set(top.flatMap(r=>r.entryIds))]}));
  }

  /* 3. how states changed — described, never scored */
  const prev=periodRangeBefore(range),prevChecks=checkins.filter(c=>inRange(c.observedAt,prev));
  const stateItems=[];let statesEnough=false;
  for(const d of activeDimensions(config)){
    const cur=chkP.map(c=>dimValue(c,d.key)).filter(v=>v!=null);
    if(cur.length<MIN_N) continue;
    statesEnough=true;
    const med=median(cur),before=prevChecks.map(c=>dimValue(c,d.key)).filter(v=>v!=null);
    const nearest=d.values.reduce((b,v)=>Math.abs(v-med)<Math.abs(b-med)?v:b,d.values[0]);
    let text=`${d.name}: чаще всего — «${dimLabel(d,nearest).toLocaleLowerCase("ru-RU")}» (по ${cur.length} ${plural.checkin(cur.length)}).`;
    if(before.length>=MIN_N){
      const mb=median(before),diff=med-mb;
      text+=diff===0?" В предыдущем периоде было так же.":` В предыдущем периоде — ${diff>0?"ниже":"выше"}.`;
    }
    stateItems.push(item("states",text,{days:[...new Set(chkP.filter(c=>dimValue(c,d.key)!=null).map(c=>dayKey(c.observedAt)))]}));
  }

  /* 4. moments worth remembering */
  const favs=inP.filter(e=>e.favorite),pool=favs.length?favs:inP.slice().sort((a,b)=>wordCount(b.body)-wordCount(a.body)).slice(0,3);
  const moments=pool.slice(0,5).map(e=>item("moments",`«${title(e)}»${entryText(e,140).rest?` — ${entryText(e,140).rest}`:""}`,{sourceIds:[e.id]}));

  /* 5. open loops */
  const loops=[],today=dayKey(now.toISOString?now.toISOString():now);
  for(const e of inP)if(!e.completedAt)loops.push(item("loops",`Не завершена: «${title(e)}»`,{sourceIds:[e.id]}));
  for(const e of inP){const n=openChecklistItems(e.body);if(n>0)loops.push(item("loops",`Незакрытые пункты (${n}) в «${title(e)}»`,{sourceIds:[e.id]}));}
  for(const e of entries){
    const dec=e.decision;
    if(e.deletedAt||!dec||!dec.revisitOn||dec.outcome) continue;
    const decidedHere=inRange(e.happenedAt,range),dueHere=dec.revisitOn>=range.from&&dec.revisitOn<=range.to,overdue=dec.revisitOn<range.from;
    if(!(decidedHere||dueHere||overdue)) continue;
    const due=dec.revisitOn<=today;
    loops.push(item("loops",`Решение «${dec.decision||title(e)}» (${dayLabel(dayKey(e.happenedAt))}): ${due?"пора вернуться и записать, что получилось":`вернуться ${dayLabel(dec.revisitOn)}`}`,{sourceIds:[e.id]}));
  }

  /* 7. questions for the next period */
  const seed=range.id,bank=[];
  const topTheme=listByType(ents,"theme")[0],topPerson=listByType(ents,"person")[0];
  if(topTheme)bank.push(...QUESTION_BANK.theme(topTheme.name));
  if(topPerson)bank.push(...QUESTION_BANK.person(topPerson.name));
  if(stateItems.length)bank.push(...QUESTION_BANK.shift);
  if(loops.length)bank.push(...QUESTION_BANK.loop);
  if(inP.length<3)bank.push(...QUESTION_BANK.quiet);
  bank.push(...QUESTION_BANK.base);
  const questions=pickStable(bank,seed,3).map(q=>item("questions",q));

  return {range,stats,hasData:inP.length>0||chkP.length>0,
    sections:{happened,entities:entityItems,states:stateItems,moments,loops,surprised:[],questions},
    statesNote:statesEnough?"Это описание ваших отметок, а не оценка и не объяснение причин.":"",
    statesThin:!statesEnough&&chkP.length>0,
    entryIds:inP.map(e=>e.id),previous:prev};
}
export function periodRangeBefore(range){return shiftPeriod(range,-1);}

export const SECTION_TITLES={
  happened:"Что произошло",entities:"Люди, места и темы",states:"Как менялось состояние",moments:"Моменты, которые стоит помнить",
  loops:"Что осталось открытым",surprised:"Что удивило",questions:"Вопросы на следующий период"
};
export const SECTION_ORDER=["happened","entities","states","moments","loops","surprised","questions"];

/** Markdown for export/print: the factual lines the user has not hidden, plus their own notes, verbatim. */
export function reviewToMarkdown(review,saved){
  const hidden=new Set(saved?.hidden||[]),lines=[`# ${capitalizeRu(review.range.label)}`,""];
  const s=review.stats;
  lines.push(`_${s.entries} ${plural.entry(s.entries)}, ${s.words} ${plural.word(s.words)}, дней с записями: ${s.activeDays}_`,"");
  for(const key of SECTION_ORDER){
    const facts=(review.sections[key]||[]).filter(f=>!hidden.has(f.id)),own=(saved?.sections?.[key]||"").trim();
    if(!facts.length&&!own) continue;
    lines.push(`## ${SECTION_TITLES[key]}`,"");
    for(const f of facts)lines.push(`- ${f.text}`);
    if(facts.length)lines.push("");
    if(own)lines.push(own,"");
  }
  return lines.join("\n").trimEnd()+"\n";
}

/** Structure for the printable annual "book": a cover, one chapter per month with the user's own words, closing notes. */
export function buildBook({range,entries,checkins,config,chapters,notes,saved,includeAll=false,now}){
  const review=buildReview({range,entries,checkins,config,chapters,notes,now});
  const inP=entries.filter(e=>!e.deletedAt&&inRange(e.happenedAt,range)).sort((a,b)=>new Date(a.happenedAt)-new Date(b.happenedAt));
  const months=[];
  for(let m=1;m<=12;m++){
    const prefix=`${parts(range.from)[0]}-${pad(m)}`;
    const list=inP.filter(e=>dayKey(e.happenedAt).startsWith(prefix));
    if(!list.length) continue;
    const chosen=includeAll?list:(list.some(e=>e.favorite)?list.filter(e=>e.favorite):list.slice().sort((a,b)=>wordCount(b.body)-wordCount(a.body)).slice(0,2)).sort((a,b)=>new Date(a.happenedAt)-new Date(b.happenedAt));
    months.push({month:MONTHS_NOM[m-1],count:list.length,entries:chosen});
  }
  return {review,months,saved,cover:{title:`${parts(range.from)[0]} год`,subtitle:`${review.stats.entries} ${plural.entry(review.stats.entries)} · ${review.stats.words} ${plural.word(review.stats.words)}`}};
}
export {excerpt};
